server:
  port: 8080
spring:
  application:
    name: web-gateway

dubbo:
  application:
    name: gateway-consumer
    qos-enable: false
  protocol:
    name: dubbo
  registry:
      address: zookeeper://127.0.0.1:2181
  consumer:
    check: false
  scan:
    base-packages: com.couglas
  metadata-report:
    address: zookeeper://127.0.0.1:2181
